name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag lhiguitab/express-randomquotes:latest

      - name: Push Docker image
        run: docker push lhiguitab/express-randomquotes:latest
